# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Marca')),
            ],
            options={
                'ordering': ['descricao'],
                'verbose_name_plural': 'Marcas',
                'verbose_name': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('criacao', models.DateTimeField(default=datetime.date(2017, 10, 10), verbose_name='Criação')),
                ('produto_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Marca')),
            ],
            options={
                'ordering': ['descricao'],
                'verbose_name_plural': 'Produtos',
                'verbose_name': 'Produto',
            },
        ),
    ]
