# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor de Compra')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
