# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20171010_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor de Compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
