# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_auto_20171011_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
    ]
