# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo',
            field=models.IntegerField(choices=[('0', 'Carro'), ('1', 'Moto')], default=0, verbose_name='Carro ou Moto?'),
        ),
        migrations.AlterField(
            model_name='config',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor Hora'),
        ),
    ]
