# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_auto_20171031_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='tipo',
            field=models.IntegerField(choices=[('1', 'Carro'), ('2', 'Moto')], default=1, verbose_name='Carro ou Moto?'),
        ),
    ]
