# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormadePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Formas de pagamento',
                'verbose_name': 'Forma de pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='venda_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Desconto')),
                ('acrescimo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Acréscimo')),
                ('data_emissao', models.DateField(default=datetime.date(2017, 10, 31), verbose_name='Data de emissão')),
                ('venda_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.FormadePagamento', verbose_name='Forma de pagamento')),
                ('venda_produto', models.ManyToManyField(through='vendas.venda_produtos', to='estoque.Produto', verbose_name='Produtos')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'verbose_name': 'Venda',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='venda_produtos',
            name='venda_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Vendas', verbose_name='Venda'),
        ),
    ]
