# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0006_auto_20171011_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormadePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['descricao'],
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto')),
                ('acrescimo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Acréscimo')),
                ('data_emissao', models.DateField(default=datetime.date(2017, 10, 11), verbose_name='Data de emissão')),
                ('venda_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.FormadePagamento', verbose_name='Forma de pagamento')),
                ('venda_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto', verbose_name='Produto')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
