# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_auto_20171017_0906'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='acrescimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Acréscimo'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_emissao',
            field=models.DateField(default=datetime.date(2017, 10, 17), verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Desconto'),
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='venda_produto',
        ),
        migrations.AddField(
            model_name='vendas',
            name='venda_produto',
            field=models.ManyToManyField(to='estoque.Produto', verbose_name='Produtos'),
        ),
    ]
