# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda_produtos',
            name='produto_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='venda_produtos',
            name='quantidade',
            field=models.IntegerField(blank=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_emissao',
            field=models.DateField(default=datetime.date(2017, 11, 1), verbose_name='Data de emissão'),
        ),
    ]
