# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 1), verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 1), verbose_name='Data de Pagamento'),
        ),
    ]
