# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20171101_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['data_pagamento'], 'verbose_name': 'Caixa', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 7), verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 7), verbose_name='Data de Pagamento'),
        ),
    ]
