# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20171107_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 9), verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='movimento',
            field=models.IntegerField(choices=[(0, 'ENTRADA'), (1, 'SAIDA')], verbose_name='Movimento'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2017, 11, 9), verbose_name='Data de Pagamento'),
        ),
        migrations.DeleteModel(
            name='Movimento',
        ),
    ]
